export type Language = 'en-US' | 'en-GB' | 'si' | 'ta';

export const TRANSLATIONS = {
  'en-US': {
    title: 'MetroSeek',
    subtitle: 'The Ultimate AI Bot for Sri Lanka',
    imageGen: 'AI Image Generation',
    ocr: 'Image & Doc Text Extraction',
    face: 'Facial Trait Analysis',
    math: 'Math & Geometry Solver',
    promptLabel: 'Enter your prompt',
    generateBtn: 'Generate',
    uploadLabel: 'Upload Image/Doc',
    analyzing: 'Analyzing...',
    resultLabel: 'Result',
    chatTitle: 'AI Chatbot',
    chatPlaceholder: 'Ask me anything...',
    send: 'Send',
    error: 'An error occurred. Please try again.',
    welcome: 'Welcome to MetroSeek. Choose a feature below to get started.',
    home: 'Home',
    about: 'About',
    contact: 'Contact',
    language: 'Language',
  },
  'en-GB': {
    title: 'MetroSeek',
    subtitle: 'The Ultimate AI Bot for Sri Lanka',
    imageGen: 'AI Image Generation',
    ocr: 'Image & Doc Text Extraction',
    face: 'Facial Trait Analysis',
    math: 'Maths & Geometry Solver',
    promptLabel: 'Enter your prompt',
    generateBtn: 'Generate',
    uploadLabel: 'Upload Image/Doc',
    analyzing: 'Analysing...',
    resultLabel: 'Result',
    chatTitle: 'AI Chatbot',
    chatPlaceholder: 'Ask me anything...',
    send: 'Send',
    error: 'An error occurred. Please try again.',
    welcome: 'Welcome to MetroSeek. Choose a feature below to get started.',
    home: 'Home',
    about: 'About',
    contact: 'Contact',
    language: 'Language',
  },
  'si': {
    title: 'MetroSeek (මෙට්‍රොසීක්)',
    subtitle: 'ශ්‍රී ලංකාව සඳහා වන අවසාන AI බොට් එක',
    imageGen: 'AI රූප නිර්මාණය',
    ocr: 'රූප සහ ලේඛන පෙළ නිස්සාරණය',
    face: 'මුහුණේ ලක්ෂණ විශ්ලේෂණය',
    math: 'ගණිත හා ජ්‍යාමිතික විසඳුම්',
    promptLabel: 'ඔබගේ විමසුම ඇතුළත් කරන්න',
    generateBtn: 'නිර්මාණය කරන්න',
    uploadLabel: 'රූපය/ලේඛනය උඩුගත කරන්න',
    analyzing: 'විශ්ලේෂණය කරමින්...',
    resultLabel: 'Result',
    chatTitle: 'AI කතාබස් (Chatbot)',
    chatPlaceholder: 'ඕනෑම දෙයක් අසන්න...',
    send: 'යවන්න',
    error: 'දෝෂයක් සිදුවිය. කරුණාකර නැවත උත්සාහ කරන්න.',
    welcome: 'MetroSeek වෙත සාදරයෙන් පිළිගනිමු. ආරම්භ කිරීමට පහත විශේෂාංගයක් තෝරන්න.',
    home: 'ප්‍රධාන පිටුව',
    about: 'අපි ගැන',
    contact: 'සම්බන්ධ වන්න',
    language: 'භාෂාව',
  },
  'ta': {
    title: 'MetroSeek (மெட்ரோசீக்)',
    subtitle: 'இலங்கைக்கான இறுதி AI போட்',
    imageGen: 'AI பட உருவாக்கம்',
    ocr: 'படம் மற்றும் ஆவண உரை பிரித்தெடுத்தல்',
    face: 'முக அம்ச பகுப்பாய்வு',
    math: 'கணிதம் மற்றும் வடிவவியலைத் தீர்க்கும் கருவி',
    promptLabel: 'உங்கள் கட்டளையை உள்ளிடவும்',
    generateBtn: 'உருவாக்கு',
    uploadLabel: 'படம்/ஆவணத்தை பதிவேற்றவும்',
    analyzing: 'பகுப்பாய்வு செய்கிறது...',
    resultLabel: 'முடிவு',
    chatTitle: 'AI சாட்போட்',
    chatPlaceholder: 'எதுவும் கேளுங்கள்...',
    send: 'அனுப்பு',
    error: 'ஒரு பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.',
    welcome: 'MetroSeek-க்கு வரவேற்கிறோம். தொடங்க கீழே உள்ள அம்சத்தைத் தேர்ந்தெடுக்கவும்.',
    home: 'முதன்மை பக்கம்',
    about: 'எங்களை பற்றி',
    contact: 'தொடர்பு கொள்ள',
    language: 'மொழி',
  }
};
